package ch.ech.ech0229;

import javax.annotation.Generated;

@Generated(value="org.minimalj.metamodel.generator.ClassGenerator")
public enum TaxableResultDecreaseReason {
	reversalOfTaxedUndisclosedReserves, contributionsToPensionFundsForBenefitOfOwnStaff, grantsToTaxExemptedLegalEntitiesDomiciledInSwitzerland, otherReason, releaseOfTaxedHiddenReserves, capitalContributions, gainsFromSaleOrRevaluationOfProperties, releaseOfTaxedProvisionsOrDepositsInSpecialFundsReservesOrDepreciationCreditedToIncomeStatement, additionsToAssetsFromDonationsGiftsAndBequests, surplusOfMembershipFees, contributionsToTheFoundationsAssets;
}