package ch.ech.ech0229;

import javax.annotation.Generated;

@Generated(value="org.minimalj.metamodel.generator.ClassGenerator", date = "2020-06-11T15:12:24.484260300")
public enum TaxableResultDecreaseReason {
	reversalOfTaxedUndisclosedReserves, contributionsToPensionFundsForBenefitOfOwnStaff, grantsToTaxExemptedLegalEntitiesDomiciledInSwitzerland, otherReason, releaseOfTaxedHiddenReserves, capitalContributions, gainsFromSaleOrRevaluationOfProperties, releaseOfTaxedProvisionsOrDepositsInSpecialFundsReservesOrDepreciationCreditedToIncomeStatement, additionsToAssetsFromDonationsGiftsAndBequests, surplusOfMembershipFees, contributionsToTheFoundationsAssets;
}