package ch.ech.ech0229;

import javax.annotation.Generated;

@Generated(value="org.minimalj.metamodel.generator.ClassGenerator", date = "2019-09-24T07:31:04.338")
public enum TaxableResultIncreaseReason {
	unjustifiedBusinessDepreciationAndCostsForAcquisitionProductionOrIncreaseInValueOfAssets, provisionsNotSubstantiatedByBusiness, unallowableDepreciationOfRevaluedAssets, contributionsToReserves, concealedProfitDistributionsAndUnjustifiedPaymentsToThirdParties, depreciationAndValueAdjustmentOfInvestmentsNoLongerJustifiedInBusinessTerms, excessiveGrants, interestOnHiddenEquity, paymentsOfBribesToPublicOfficials, eliminationOfBusinessJustificationOfProvisions, bookprofitsFromHigherValuationOfRealEstate, bookprofitsFromHigherValuationOfInvestments, anticipatedProfits, liquidationGains, nonDeductibleProvisionsOrDepositsInSpecialFundsOrReserves, nonDeductibleDepreciation, taxableIncomeNotCreditedToIncomeStatement, otherReason;
}