/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientOptionsPanel.java
 *
 * Created on 20.07.2010, 08:42:27
 */

package ch.openech.client.ewk;

/**
 * 
 * @author bruno
 */
public class ClientOptionsPanel extends javax.swing.JPanel {

	/** Creates new form ClientOptionsPanel */
	public ClientOptionsPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkBoxCodesFree = new javax.swing.JCheckBox();
        checkBoxCodesClear = new javax.swing.JCheckBox();
        checkBoxDateFormat = new javax.swing.JCheckBox();
        checkBoxShowXml = new javax.swing.JCheckBox();
        checkBoxShowLog = new javax.swing.JCheckBox();
        checkBoxGenerateData = new javax.swing.JCheckBox();
        checkBoxMenuBaseDelivery = new javax.swing.JCheckBox();

        checkBoxCodesFree.setText("Codes erlauben freie Eingabe");
        checkBoxCodesFree.setName("codesFree"); // NOI18N

        checkBoxCodesClear.setText("Codes erlauben Löschung (auch bei zwingender Eingabe)");
        checkBoxCodesClear.setName("codesClear"); // NOI18N

        checkBoxDateFormat.setText("Format Kontextmenu bei Datum");
        checkBoxDateFormat.setName("dateFormat"); // NOI18N

        checkBoxShowXml.setText("Anzeige der XML - Daten");
        checkBoxShowXml.setName("showXml"); // NOI18N

        checkBoxShowLog.setText("Log - Fenster sichtbar");
        checkBoxShowLog.setName("showLog"); // NOI18N

        checkBoxGenerateData.setText("Datengenerierung / Automatisches Ausfüllen");
        checkBoxGenerateData.setName("generateData"); // NOI18N

        checkBoxMenuBaseDelivery.setText("Basislieferung als Menu anbieten");
        checkBoxMenuBaseDelivery.setName("menuBaseDelivery"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxCodesFree)
                            .addComponent(checkBoxCodesClear))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxDateFormat)
                        .addContainerGap(144, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxShowXml)
                        .addContainerGap(172, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxShowLog)
                        .addContainerGap(186, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxGenerateData)
                        .addContainerGap(77, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxMenuBaseDelivery)
                        .addContainerGap(134, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxCodesFree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxCodesClear)
                .addGap(8, 8, 8)
                .addComponent(checkBoxDateFormat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBoxShowXml)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxShowLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBoxGenerateData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxMenuBaseDelivery)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxCodesClear;
    private javax.swing.JCheckBox checkBoxCodesFree;
    private javax.swing.JCheckBox checkBoxDateFormat;
    private javax.swing.JCheckBox checkBoxGenerateData;
    private javax.swing.JCheckBox checkBoxMenuBaseDelivery;
    private javax.swing.JCheckBox checkBoxShowLog;
    private javax.swing.JCheckBox checkBoxShowXml;
    // End of variables declaration//GEN-END:variables

}
