package ch.ech.ech0196;

import javax.annotation.Generated;

@Generated(value="org.minimalj.metamodel.generator.ClassGenerator", date = "2019-09-24T07:31:03.534")
public enum SecurityType {
	BOND_BOND, BOND_OPTION, BOND_CONVERTIBLE, COINBULL_COINGOLD, COINBULL_GOLD, COINBULL_PALLADIUM, COINBULL_PLATINUM, COINBULL_SILVER, CURRNOTE_CURRENCY, CURRNOTE_CURRYEAR, DEVT_COMBINEDPRODUCT, DEVT_FUNDSIMILARASSET, DEVT_INDEXBASKET, FUND_ACCUMULATION, FUND_DISTRIBUTION, FUND_REALESTATE, LIBOSWAP_LIBOR, LIBOSWAP_SWAP, OPTION_CALL, OPTION_PHANTOM, OPTION_PUT, SHARE_BEARERCERT, SHARE_BONUS, SHARE_COMMON, SHARE_COOP, SHARE_LIMITED, SHARE_NOMINAL, SHARE_PARTCERT, SHARE_PREFERRED, SHARE_TRANSFERABLE;
}